version: '3.8'

services:
  wagl-frontend-demo:
    build: .
    container_name: wagl-frontend-demo
    ports:
      - "3000:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      # Mount for development - comment out for production
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - wagl-network

  # Optional: Add a simple CORS proxy if needed
  cors-proxy:
    image: redocly/cors-anywhere
    container_name: wagl-cors-proxy
    ports:
      - "8080:8080"
    environment:
      - CORS_PROXY_ORIGINS=*
    restart: unless-stopped
    networks:
      - wagl-network
    profiles:
      - cors-proxy

networks:
  wagl-network:
    driver: bridge